package ru.alepar.zx80.integration

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import ru.alepar.zx80.machine.Beeper
import ru.alepar.zx80.machine.BorderState
import ru.alepar.zx80.machine.Keyboard
import ru.alepar.zx80.machine.Spectrum48k
import ru.alepar.zx80.machine.SpectrumIoBus
import ru.alepar.zx80.machine.SpectrumKey
import ru.alepar.zx80.machine.tape.TapParser

class TapeLoadBasicGameTest {

    @Test
    @Tag("integration")
    fun `LOAD tape runs BASIC guessing game and shows prompt on screen`() {
        val machine = Spectrum48k()
        val keyboard = Keyboard()
        machine.cpu.io = SpectrumIoBus(keyboard, Beeper(machine.cpu), BorderState())
        machine.reset()

        // Pre-load the guessing-game tape so the ROM trap can serve it
        machine.tapeDeck.loadTape(TapParser.parseTap(GUESS_TAP))

        // Boot to BASIC prompt (~82 frames for ROM memory test; 200 is comfortable headroom)
        repeat(200) { machine.runFrame() }

        // Type: LOAD ""  then Enter
        // In K-mode: J = LOAD keyword, SS+P = quote character
        val type = SpectrumTypist(machine, keyboard)
        type.press(SpectrumKey.J)
        type.withMod(SpectrumKey.SYMBOL_SHIFT, SpectrumKey.P)
        type.withMod(SpectrumKey.SYMBOL_SHIFT, SpectrumKey.P)
        type.enter()

        // Allow time for tape load (ROM trap is instant) + BASIC auto-run to line 60 PRINT
        repeat(100) { machine.runFrame() }

        val reader = ScreenReader(machine.mem)
        val screenText = reader.asText().joinToString("\n")
        assertThat(reader.contains("GUESS 1-100"))
            .`as`("expected 'GUESS 1-100' on screen after tape autorun; actual:\n$screenText")
            .isTrue
    }

    companion object {
        /**
         * NUMBER GUESSING GAME in ZX Spectrum BASIC tokenized .tap format (266 bytes). The program
         * auto-starts at line 20 (RANDOMIZE). Lines: 10 REM NUMBER GUESSING GAME 20 RANDOMIZE 30
         * LET n=INT(RND*100)+1 40 LET g=0 50 CLS 60 PRINT "GUESS 1-100" 70 INPUT "YOUR GUESS? ";a
         * 80 LET g=g+1 90 IF a<n THEN PRINT "TOO LOW" 100 IF a>n THEN PRINT "TOO HIGH" 110 IF a=n
         * THEN PRINT "CORRECT! ";g;" GUESSES": STOP 120 GO TO 70
         */
        val GUESS_TAP =
            byteArrayOf(
                19,
                0,
                0,
                0,
                71,
                85,
                69,
                83,
                83,
                32,
                32,
                32,
                32,
                32,
                -15,
                0,
                20,
                0,
                -15,
                0,
                99,
                -13,
                0,
                -1,
                0,
                10,
                23,
                0,
                -22,
                32,
                78,
                85,
                77,
                66,
                69,
                82,
                32,
                71,
                85,
                69,
                83,
                83,
                73,
                78,
                71,
                32,
                71,
                65,
                77,
                69,
                13,
                0,
                20,
                2,
                0,
                -7,
                13,
                0,
                30,
                26,
                0,
                -15,
                110,
                61,
                -70,
                40,
                -91,
                42,
                49,
                48,
                48,
                14,
                0,
                0,
                100,
                0,
                0,
                41,
                43,
                49,
                14,
                0,
                0,
                1,
                0,
                0,
                13,
                0,
                40,
                11,
                0,
                -15,
                103,
                61,
                48,
                14,
                0,
                0,
                0,
                0,
                0,
                13,
                0,
                50,
                2,
                0,
                -5,
                13,
                0,
                60,
                15,
                0,
                -11,
                34,
                71,
                85,
                69,
                83,
                83,
                32,
                49,
                45,
                49,
                48,
                48,
                34,
                13,
                0,
                70,
                18,
                0,
                -18,
                34,
                89,
                79,
                85,
                82,
                32,
                71,
                85,
                69,
                83,
                83,
                63,
                32,
                34,
                59,
                97,
                13,
                0,
                80,
                13,
                0,
                -15,
                103,
                61,
                103,
                43,
                49,
                14,
                0,
                0,
                1,
                0,
                0,
                13,
                0,
                90,
                18,
                0,
                -6,
                97,
                60,
                110,
                32,
                -53,
                32,
                -11,
                34,
                84,
                79,
                79,
                32,
                76,
                79,
                87,
                34,
                13,
                0,
                100,
                19,
                0,
                -6,
                97,
                62,
                110,
                32,
                -53,
                32,
                -11,
                34,
                84,
                79,
                79,
                32,
                72,
                73,
                71,
                72,
                34,
                13,
                0,
                110,
                35,
                0,
                -6,
                97,
                61,
                110,
                32,
                -53,
                32,
                -11,
                34,
                67,
                79,
                82,
                82,
                69,
                67,
                84,
                33,
                32,
                34,
                59,
                103,
                59,
                34,
                32,
                71,
                85,
                69,
                83,
                83,
                69,
                83,
                34,
                58,
                -30,
                13,
                0,
                120,
                11,
                0,
                -20,
                32,
                55,
                48,
                14,
                0,
                0,
                70,
                0,
                0,
                13,
                80,
            )
    }
}
